import {StyleSheet} from 'react-native';
import {useColors, useFonts} from '@theme';

// eslint-disable-next-line react-hooks/rules-of-hooks
const colors = useColors();
// eslint-disable-next-line react-hooks/rules-of-hooks
const fonts = useFonts();

const styles = StyleSheet.create({
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    borderRadius: 50,
  },
  inputContainer: {
    width: ' 100%',
    marginBottom: 10,
  },
  inputContainerModal: {
    flex: 1,
    width: ' 100%',
    paddingTop: 21,
  },
  searchInput: {
    flex: 1,
    height: 40,
  },
  searchIcon: {
    marginRight: 10,
  },
  selectTextStyle: {
    fontSize: 12,
    paddingHorizontal: '4%',
  },
  selectInput: {
    borderRadius: 8,
    marginBottom: 3,
  },
  inputLabel: {
    marginBottom: 10,
    color: colors.text.main,
    fontFamily: 'Avenir',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
  },
  textAreaError: {
    borderColor: colors.status.error.main,
  },
  errorText: {
    marginTop: 10,
    color: colors.status.error.main,
  },
  inputLabelWithIcon: {
    marginBottom: 10,
    fontFamily: 'Avenir',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: colors.text.main,
  },
  input: {
    flex: 1,
    height: 40,
    width: '100%',
    fontFamily: 'Lato-Regular',
    lineHeight: 14,
    fontSize: 12,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: '8%',
    marginBottom: 18,
  },
  inputWithIcon: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    width: '100%',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: '4%',
    marginBottom: 18,
    fontFamily: 'Avenir',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 25,
    letterSpacing: 0,
    textAlign: 'left',
    backgroundColor: colors.common.white,
    color: colors.text.main,
    overflow: 'hidden',
  },
  inputWithIconInactive: {
    borderColor: colors.border.main,
  },
  inputWithIconActive: {
    borderColor: colors.border.black,
  },
  inputWithIconError: {
    borderColor: colors.status.error.main,
  },
  inputWithIconText: {
    flex: 1,
    marginLeft: 10,
    paddingVertical: 10,
    height: 52,
  },
  inputIcon: {
    height: 24,
    width: 24,
  },
  inputIconService: {
    height: 50,
    width: 50,
  },
  addressInputContainer: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'left',
    fontFamily: 'Lato-Regular',
    lineHeight: 14,
    fontSize: 12,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: '8%',
    marginBottom: 18,
  },
  tripleHeight: {
    height: 90,
    lineHeight: 24,
    fontSize: 14,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  selectInputContainer: {
    marginBottom: 1,
  },
  selectInputWithZindex: {
    zIndex: 1,
  },
  selectInputWithRelative: {
    position: 'relative',
  },
  selectInputWithoutZindex: {
    zIndex: 0,
    marginBottom: 20,
  },
  textArea: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingLeft: 14,
    paddingRight: 14,
    minHeight: 100,
    width: 'auto',
    lineHeight: 25,
  },
  textAreaActive: {
    borderColor: colors.border.black,
  },
  textAreaInactive: {
    borderColor: colors.border.main,
  },
  fullWidth: {
    width: '100%',
  },
  locationIconContainer: {
    height: 50,
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationIconImg: {
    height: 24,
  },
  disabledStyle: {
    opacity: 0.5,
  },
  error: {
    fontSize: 12,
    fontFamily: 'Lato-Regular',
    marginBottom: 10,
  },
  addressInputView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressInputMaxWidth: {
    maxWidth: '95%',
  },
  inputSuffix: {
    lineHeight: 24,
    width: 24,
    textAlign: 'center',
  },
  dropdownIcon: {
    transform: [{rotate: '0deg'}],
  },
  dropdownIconActive: {
    transform: [{rotate: '180deg'}],
  },
  dropdownListContainer: {
    shadowColor: colors.shadow.dropdownList,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    position: 'absolute',
    zIndex: 9,
    width: '100%',
    top: 60,
  },
  dropdownListScrollable: {
    borderRadius: 8,
    borderColor: colors.border.main,
    borderWidth: 1,
  },
  dropdownListItem: {
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: colors.common.gray,
    justifyContent: 'center',
    backgroundColor: colors.common.white,
    padding: 15,
    overflow: 'hidden',
  },
  dropdownListItemLabel: {
    ...fonts.secondaryText,
    lineHeight: 25,
    letterSpacing: 0,
    textAlign: 'left',
  },
  dropdownInput: {
    ...fonts.secondaryText,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    width: '100%',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: '4%',
    marginBottom: 8,
    lineHeight: 25,
    letterSpacing: 0,
    textAlign: 'left',
    backgroundColor: colors.common.white,
    color: colors.text.main,
    overflow: 'hidden',
  },
  listContainer: {
    backgroundColor: colors.common.white,
    borderColor: colors.border.main,
    marginTop: 10,
    width: '100%',
    borderWidth: 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    paddingVertical: 8,
    shadowColor: 'transparent',
    paddingBottom: 0,
  },
  textInputContainer: {
    ...fonts.secondaryText,
    maxWidth: '90%',
  },
  floatIcon: {
    position: 'absolute',
    right: 16,
    top: 16,
  },
  autoCompleteContainer: {
    borderColor: colors.border.main,
  },
  inputRow: {
    flexDirection: 'row',
    marginBottom: 18,
    width: '100%',
  },
  addressTextInputContainer: {
    paddingVertical: 6,
    paddingHorizontal: '6%',
    borderBottomWidth: 1,
    borderColor: colors.border.main,
  },
  addressTextInput: {
    ...fonts.secondaryText,
    color: colors.text.main,
  },
  suggestionHeight: {
    height: 160,
  },
  dropdownInputBottomSheet: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 52,
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: '4%',
    marginBottom: 8,
    fontFamily: fonts.secondaryText.fontFamily,
    fontSize: fonts.secondaryText.fontSize,
    fontWeight: fonts.secondaryText.fontWeight,
    lineHeight: 25,
    letterSpacing: 0,
    textAlign: 'left',
    backgroundColor: colors.common.white,
    color: colors.text.main,
  },
  dropdownInputBottomSheetActive: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 52,
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: '4%',
    marginBottom: 8,
    fontFamily: 'Avenir',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 25,
    letterSpacing: 0,
    textAlign: 'left',
    backgroundColor: colors.common.white,
    color: colors.text.main,
  },
  textGray: {
    color: colors.text.secondary,
  },
  textBlack: {
    color: colors.text.secondarmain,
  },
  containerDropdownBottom: {
    flex: 1,
    padding: 10,
  },
  containerAlert: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    backgroundColor: colors.status.info.background,
    paddingTop: 8,
    paddingBottom: 8,
    paddingRight: 14,
    paddingLeft: 14,
    borderRadius: 4,
    marginTop: 20,
  },
  titleAlert: {
    paddingLeft: 13.5,
    color: colors.common.white,
    fontWeight: '400',
  },
  containerOptions: {
    borderColor: colors.border.main,
    borderWidth: 1,
    borderRadius: 4,
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
  },
  imgTitleOption: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerIcon: {
    backgroundColor: colors.background.background1,
    width: 50,
    height: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  containerIcon2: {
    backgroundColor: colors.background.background1,
    width: 40,
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  iconImg: {
    height: 20,
  },
  titleOption: {
    color: colors.text.main,
    fontWeight: '500',
  },
  dataOption: {
    color: colors.text.secondary,
    width: '90%',
  },
  priceOption: {
    color: colors.text.main,
    fontWeight: '900',
  },
  displayContainerDropdownModal: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  paddingLeft10: {
    paddingLeft: 10,
  },
  pickerInput: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
  },
  zIndexTwo: {
    zIndex: 2,
  },
  textContainer: {
    flex: 1,
    flexDirection: 'row',
    marginBottom: 15,
    justifyContent: 'center',
  },
  radioButtonSection: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border.main,
    borderRadius: 12,
  },
  radioButton: {
    height: 46,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
  },
  radioButton__title: {
    paddingLeft: 16,
    color: colors.text.main,
    fontSize: fonts.label.fontSize,
    fontWeight: fonts.label.fontWeight,
  },
  radioButton__circle: {
    width: 20,
    height: 20,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: colors.border.secondary,
  },
  dropdownBottom: {
    width: '100%',
  },
  dropdownBottom__label: {
    paddingBottom: 10,
    fontSize: fonts.boldTitle.fontSize,
    fontWeight: fonts.boldTitle.fontWeight,
    color: fonts.boldTitle.color,
  },
  inputDropdown: {
    borderWidth: 2,
    borderColor: colors.border.main,
    width: '100%',
    height: 52,
    flexDirection: 'row',
    paddingRight: 16,
    paddingLeft: 16,
    borderRadius: 4,
  },
  inputDropdownIconAndLabel: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  inputDropdownIconAndLabel__display: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputDropdown__image: {
    paddingRight: 14,
  },
  inputDropdown__iconAndLabel__placeholder: {
    fontSize: fonts.secondaryText.fontSize,
    fontWeight: fonts.secondaryText.fontWeight,
    color: colors.text.secondary,
  },
  inputDropdown__iconAndLabel__placeholder_activate: {
    fontSize: fonts.secondaryText.fontSize,
    fontWeight: fonts.secondaryText.fontWeight,
    color: colors.text.main,
  },
  inputRadioButton: {
    height: 46,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border.main,
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 14,
    paddingLeft: 14,
  },
  inputRadioButtonActive: {
    height: 46,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border.selected,
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 14,
    paddingLeft: 14,
  },
  dataInputRadioButton__label: {
    color: colors.text.main,
    fontSize: fonts.label.fontsize,
    fontWeight: fonts.label.fontWeight,
  },
  dataInputRadioButton__description: {
    color: colors.text.secondary,
    fontSize: fonts.label.fontsize,
    fontWeight: fonts.label.fontWeight,
  },
  customCheckBox: {
    paddingHorizontal: 26,
    paddingVertical: 23,
    borderWidth: 1,
    borderColor: colors.border.main,
    marginBottom: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customCheckBox__title: {
    color: colors.text.main,
    fontSize: 14,
  },
  customCheckBox__true: {
    height: 20,
    width: 20,
    borderWidth: 7,
    borderColor: colors.common.main,
    borderRadius: 50,
  },
  customCheckBox__false: {
    height: 20,
    width: 20,
    borderWidth: 2,
    borderColor: colors.border.secondary,
    borderRadius: 50,
  },
});

export default styles;
